"""Household waste item labels — single source of truth.

Labels are S3-safe strings (lowercase letters, digits, hyphens)
used as directory prefixes when storing training images.
"""

import re

ALL_LABELS_LIST: list[str] = [
    "aerosol-can",
    "aluminum-can",
    "aluminum-foil",
    "aluminum-tray",
    "backpack",
    "battery",
    "bedsheet",
    "beer-bottle",
    "bread",
    "broken-glass",
    "bubble-wrap",
    "candy-wrapper",
    "cardboard-box",
    "cell-phone",
    "ceramic-mug",
    "ceramic-plate",
    "cereal-box",
    "charger",
    "chip-bag",
    "cleaning-chemical",
    "clothing",
    "coffee-filter",
    "coffee-grounds",
    "computer-monitor",
    "cotton-swab",
    "crayon",
    "curtain",
    "dental-floss",
    "detergent-bottle",
    "disposable-diaper",
    "egg-carton-paper",
    "eggshell",
    "envelope",
    "fire-extinguisher",
    "flower",
    "fruit-scraps",
    "glass-bottle",
    "glass-container",
    "glass-cup",
    "glass-jar",
    "grass-clippings",
    "headphones",
    "houseplant",
    "junk-mail",
    "keyboard",
    "laptop",
    "leaves",
    "light-bulb-fluorescent",
    "light-bulb-incandescent",
    "light-bulb-led",
    "magazine",
    "marker",
    "metal-lid",
    "metal-utensil",
    "mirror",
    "motor-oil",
    "mouse",
    "newspaper",
    "notebook",
    "nutshell",
    "office-paper",
    "paint",
    "paint-can",
    "paper-bag",
    "paper-napkin",
    "paper-plate",
    "paper-towel-roll",
    "parchment-paper",
    "pasta",
    "pen",
    "pesticide",
    "phone-book",
    "plastic-bag",
    "plastic-bottle",
    "plastic-bucket",
    "plastic-cup",
    "plastic-food-container",
    "plastic-jug",
    "plastic-lid",
    "plastic-tub",
    "plastic-wrap",
    "power-cord",
    "prescription-medication",
    "propane-tank",
    "purse",
    "rice",
    "rubber-band",
    "rug",
    "sanitary-product",
    "shampoo-bottle",
    "shoes",
    "shredded-paper",
    "shrink-wrap",
    "smoke-detector",
    "steel-can",
    "straw",
    "stuffed-animal",
    "styrofoam-container",
    "styrofoam-packing",
    "tablet",
    "tea-bag",
    "thermometer",
    "tin-can",
    "tissue",
    "towel",
    "vegetable-scraps",
    "wax-paper",
    "window-glass",
    "wine-bottle",
    "wire-hanger",
    "wrapping-paper",
    "yard-trimmings",
    "yogurt-container",
    "zip-lock-bag",
]

ALL_LABELS: frozenset[str] = frozenset(ALL_LABELS_LIST)

_S3_SAFE_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def is_valid_label(value: str) -> bool:
    """Check whether *value* is a recognized item label."""
    return value in ALL_LABELS


def is_s3_safe(value: str) -> bool:
    """Check whether *value* is safe for use as an S3 key prefix."""
    return bool(_S3_SAFE_RE.match(value))
