"""Household waste item labels — single source of truth.

Labels are S3-safe strings (lowercase letters, digits, hyphens)
used as directory prefixes when storing training images.
"""

import re

ALL_LABELS_LIST: list[str] = [
    "aerosol-can",
    "air-conditioner",
    "aluminum-can",
    "aluminum-foil",
    "battery-button",
    "battery-car",
    "battery-rechargeable",
    "battery-single-use",
    "bed-frame",
    "bedsheet",
    "belt",
    "blender",
    "bookcase",
    "bread",
    "brick",
    "bubble-wrap",
    "cardboard-box",
    "cd-dvd",
    "cell-phone",
    "chainsaw",
    "chair",
    "charger",
    "clothing",
    "coffee-capsule",
    "coffee-cup-disposable",
    "coffee-grounds",
    "computer-monitor",
    "concrete",
    "cooking-oil",
    "cork",
    "couch",
    "curtain",
    "desk",
    "detergent-bottle",
    "dishwasher",
    "drill",
    "dryer",
    "e-cigarette",
    "e-reader",
    "egg-carton",
    "electric-razor",
    "electric-toothbrush",
    "envelope",
    "eyeglasses",
    "flower",
    "fluorescent-tube",
    "food-processor",
    "food-waste",
    "freezer-bag",
    "fridge",
    "fruit-scraps",
    "game-console",
    "garden-chemical",
    "gas-bottle",
    "glass-bottle",
    "glass-container",
    "glass-jar",
    "grass-clippings",
    "hard-drive",
    "hat",
    "headphones",
    "ink-cartridge",
    "juice-box",
    "kettle",
    "keyboard",
    "laptop",
    "leaves",
    "light-bulb-fluorescent",
    "light-bulb-incandescent",
    "light-bulb-led",
    "magazine",
    "mattress",
    "meat",
    "medicine",
    "metal-drum",
    "microwave",
    "milk-carton",
    "mixer",
    "motor-oil",
    "mouse",
    "newspaper",
    "office-paper",
    "paint",
    "paint-can",
    "phone-book",
    "pizza-box",
    "plasterboard",
    "plastic-bag",
    "plastic-bottle",
    "plastic-container",
    "plastic-jug",
    "plastic-wrap",
    "polystyrene-container",
    "pool-chemical",
    "printer",
    "printer-cartridge",
    "rice-cooker",
    "scanner",
    "scrap-metal",
    "shoes",
    "shopping-bag",
    "shrink-wrap",
    "soft-plastic",
    "speaker",
    "steel-can",
    "table",
    "tablet",
    "tea-bag",
    "television",
    "tin-can",
    "tire",
    "toaster",
    "toner-cartridge",
    "towel",
    "vegetable-scraps",
    "vhs-tape",
    "wardrobe",
    "washing-machine",
    "waxed-cardboard",
    "webcam",
    "wire-hanger",
    "x-ray-film",
    "yard-trimmings",
    "zip-lock-bag",
]

ALL_LABELS: frozenset[str] = frozenset(ALL_LABELS_LIST)

_S3_SAFE_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def is_valid_label(value: str) -> bool:
    """Check whether *value* is a recognized item label."""
    return value in ALL_LABELS


def is_s3_safe(value: str) -> bool:
    """Check whether *value* is safe for use as an S3 key prefix."""
    return bool(_S3_SAFE_RE.match(value))
